(brave) Fix Brave package version detection / automation
chocolatey-community/chocolatey-packages pull request #1837
Opened 2022-04-01 16:31 UTC by pauby

## Description
Fixed the detection of the Brave browser software versions.

## Motivation and Context
The automation for detecting the software versions of Brave was broken. I've used the feeds suggested in [this comment](https://github.com/chocolatey-community/chocolatey-packages/issues/1791#issuecomment-1030152913). Because there is a version returned does not mean there is a Windows artefact for it. So added some code to test if the software is actually there.

## How Has this Been Tested?
I ran the update.ps1 script with the current version numbers (from the feeds) and using different version numbers fed into the code and checked the created nupkg files. Somebody with more experience of how the builds work here would be better placed to do more extensive testing.

## Screenshot (if appropriate, usually isn't needed):
N/A

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

2022-04-06 08:13 UTC, pauby commented
I've converted this to Draft as it's very broken now (table releases URL no longer returns a version but actually downloads the software ...)

2022-04-07 13:17 UTC, AdmiringWorm requested changes
Just a couple of empty lines that need to be removed from the description, otherwise this looks good to me

2022-04-07 13:17 UTC, AdmiringWorm commented on automatic/brave/README-beta.md
> +
Please remove this empty line, as it won't show up as expected once pushed to CCR.

2022-04-07 13:17 UTC, AdmiringWorm commented on automatic/brave/README-release.md
> +
Please remove this empty line, as it won't show up as expected once pushed to CCR.

2022-04-08 10:37 UTC, pauby commented
This is ready for review again @AdmiringWorm

2022-04-08 10:45 UTC, AdmiringWorm approved these changes
LGTM

2022-04-08 10:45 UTC, merged

2022-04-08 10:45 UTC, AdmiringWorm commented
@pauby your changes have been merged, thanks for your contribution 👍