(everything) remove es.exe and add notice
chocolatey-community/chocolatey-packages pull request #1909
Opened 2022-06-11 02:44 UTC by TheCakeIsNaOH

## Description

This removes the Everything Command Line, es.exe and adds a notice that it can be installed with the `es` package.

## Motivation and Context

Part of #1705 

## How Has this Been Tested?

`update.ps1` tested locally. 
Updated package installed and uninstalled in the test environment.

## Screenshot (if appropriate, usually isn't needed):

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

2022-06-11 09:44 UTC, AdmiringWorm requested changes

2022-06-11 09:44 UTC, AdmiringWorm commented on automatic/everything/tools/chocolateyInstall.ps1
> +Write-Host "It now can be installed via the 'es' package"
```suggestion
Write-Warning "The Everything Command Line, es.exe has been removed from this package."
Write-Warning "It now can be installed via the 'es' package"
```

2022-06-11 20:44 UTC, TheCakeIsNaOH commented on automatic/everything/tools/chocolateyInstall.ps1
> +Write-Host "It now can be installed via the 'es' package"
Done.

2022-06-13 08:26 UTC, AdmiringWorm commented
The changes look good to me, however not approving and merging the PR until the `es` package is approved on the Chocolatey Community Repository.

2022-06-21 12:33 UTC, AdmiringWorm approved these changes
LGTM

2022-06-21 12:34 UTC, merged

2022-06-21 12:35 UTC, AdmiringWorm commented
@TheCakeIsNaOH your changes have been merged, thanks for your contribution 👍