(vagrant) Update to match new filenames
chocolatey-community/chocolatey-packages pull request #1975
Opened 2022-08-18 17:36 UTC by pauby

## Description
Looks like Vagrant have changed the filename and the links on the page being scraped.

## Motivation and Context
Fixes #1973 

## How Has this Been Tested?
Ran the `update.ps1` file and checked the amended `.nuspec` and `chocolateyInstall.ps1`

## Screenshot (if appropriate, usually isn't needed):

N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

2022-08-18 20:12 UTC, gep13 requested changes

2022-08-18 20:12 UTC, gep13 commented on automatic/vagrant/update.ps1
>      $url = 'https://releases.hashicorp.com'
Is this not needed anymore?

2022-08-19 11:11 UTC, pauby commented on automatic/vagrant/update.ps1
>      $url = 'https://releases.hashicorp.com'
Good catch. No it's not.

2022-08-19 11:16 UTC, pauby commented on automatic/vagrant/update.ps1
>      $url = 'https://releases.hashicorp.com'
Fixed.

2022-09-04 17:32 UTC, gep13 approved these changes
LGTM!

2022-09-04 17:32 UTC, merged

2022-09-04 17:33 UTC, gep13 commented
@pauby thanks for getting this fixed up!