(dropbox) Update for 64 bit install inclusion
chocolatey-community/chocolatey-packages pull request #2019
Opened 2022-10-18 23:58 UTC by RedBaron2

@gep13 @AdmiringWorm @majkinetor 
## Description

This will update this package to install 64 bit versions that dropbox has now made available.

## Motivation and Context

This was requested in issue #2004 

## How Has this Been Tested?

Appveyor and local intranet

## Screenshot (if appropriate, usually isn't needed):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](add_link_to_original_repository_location)
- [Open Issues](link_to_the_generic_location_of_open_issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [x] Issue #2004 
  - [ ] Issue 2 Link
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-packages/wiki/Package-migration-process) have been followed

2022-10-25 08:29 UTC, AdmiringWorm requested changes
How do an upgrade from an existing version of dropbox that had 32bit installed behave? Will it automatically remove the 32bit and install the 64bit? Will it install 64bit side by side? These are some of the questions that need to be answered before it can be pulled in.

If it installs 64bit side by side, we need special handling in the package to remove the 32bit version first.

2022-10-27 21:32 UTC, RedBaron2 commented
@AdmiringWorm 
It appears Dropbox uses the same directory as the 32bit install. Just the executable files are changed to the 64bit versions.

2022-11-11 10:44 UTC, AdmiringWorm approved these changes

2022-11-11 10:46 UTC, merged

2022-11-11 10:48 UTC, AdmiringWorm commented
@RedBaron2 I took the liberty of combining your two commits into one, and fix the commit message, and have merged the changes. Thank you for your contribution.

This change will be part of any new packages being pushed to the Chocolatey Community Repository.