(k9s) Switch AU to Get-GitHubRelease
chocolatey-community/chocolatey-packages pull request #2059
Opened 2022-11-09 16:03 UTC by moebius87

**(k9s) Switch AU to Get-GitHubRelease**

## Description
Switch the method used by update.ps1 to get the release download url from the GitHub releases pages from a simple _Invoke-WebRequest_ to _Get-GitHubRelease_ script 

## Motivation and Context
_update.ps1_ script no longer works ( #1999 ) because of the GitHub frontend changes ( #2007 )

## How Has this Been Tested?
Contains minimal changes tested locally

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [X] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [X] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [X] The changes only affect a single package (not including meta package).

2022-11-10 01:13 UTC, linjicong submitted a review, later dismissed

2022-11-18 11:21 UTC, kipusoep approved these changes

2022-11-25 16:03 UTC, moebius87 commented
@AdmiringWorm we need your help :) Could you review and complete the PR please?

2022-11-25 17:01 UTC, pauby requested changes
Most of the information that this script constructed, is now returned from the GitHub API request.

Take a look at the hashtable returned from GetLatest(). URL64 is in the `$asset.browser_download_url`. `ReleaseNotes` is returned in `$asset.body`. `ReleaseUrl` is returned in `$asset.html_url`

2022-11-25 17:01 UTC, pauby commented
@moebius87 Please don't ping people on PR reviews. @AdmiringWorm is not the only person who can review PR's in here.

2022-12-21 15:09 UTC, moebius87 commented on automatic/k9s/update.ps1
>    $filename64 = Split-Path $url -Leaf
the curly bracket for closing the if statement is missing

2022-12-21 15:58 UTC, moebius87 commented
I'm sorry @pauby it was only because I saw that he was the last active user on the project. You're right, I won't do it again.

2023-01-30 17:51 UTC, pauby commented
`update.ps1` run fails:

```
PS C:\Users\vagrant\Desktop\k9s> .\update.ps1
k9s - checking updates using AU version 2022.10.24

URL check
Can't validate URL
Exception calling "GetResponse" with "0" argument(s): "The request was aborted: The connection was closed
unexpectedly.":https://github.com/derailed/k9s/releases/download/v0.27.0/
At C:\Program Files\WindowsPowerShell\Modules\AU\2022.10.24\Public\Update-Package.ps1:110 char:67
+ ... heck_url $url -Options $Latest.Options) { throw "${res}:$url" } else  ...
+                                               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Can't validate ...wnload/v0.27.0/:String) [], RuntimeException
    + FullyQualifiedErrorId : Can't validate URL
    Exception calling "GetResponse" with "0" argument(s): "The request was aborted: The connection was closed unexpectedly.":https://github.com/derailed/k9s/releases/download/v0.27.0/
```

It looks like the regular expression isn't being matched so the URL's are not being formed properly. The releases of this software don't always include a Windows_x86_64.tar.gz ([v0.27](https://github.com/derailed/k9s/releases/tag/v0.27.0) for example does not).

2023-03-06 04:01 UTC, closed without merging