(ungoogled-chromium) Migrate package
chocolatey-community/chocolatey-packages pull request #2113
Opened 2023-01-15 16:28 UTC by TakataSanshiro

## Description
embedded and automated ungoogled-chromium.

## Motivation and Context
automation is needed since ungoogled-chromium is updated frequently.

## How Has this Been Tested?
Chocolatey testing environment.

## Screenshot (if appropriate, usually isn't needed):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

2023-01-15 17:05 UTC, pauby commented
I don't see an issue or discussion for this. Did you follow the [migration guidelines](https://github.com/chocolatey-community/chocolatey-packages/wiki/Package-migration-process)?

2023-01-17 14:56 UTC, TakataSanshiro commented
I didn't see that. I'll open a new discussion.

2023-02-03 11:50 UTC, AdmiringWorm commented
Moving this PR into draft until we a discussion has been created, and we have decided whether to accept the package into this repository.

2023-04-14 11:34 UTC, AdmiringWorm commented
Moving to draft until user has done as asked in the created discussion #2119

2023-05-07 15:41 UTC, TakataSanshiro commented
https://github.com/chocolatey-community/chocolatey-packages/issues/2213

2023-07-22 19:31 UTC, pauby requested changes
This is using the Zip install which is just putting this files into the tools folder. There is also an EXE installer.

Should this package not be changed to a virtual package, and a `ungoogled-chriomum.portable` package created using this code? That would allow somebody to create an `ungoogled-chromium.install` package and everything would be much cleaner.

2023-07-22 19:31 UTC, pauby commented on automatic/ungoogled-chromium/update.ps1
> +function global:au_GetLatest {
There is a `Get-GitHubRelease` function that will do a lot of this work now.

2023-07-30 16:48 UTC, TakataSanshiro commented
This issue has already been fixed.
> There are many times failed when pushing embedded packages from my pc.

I have no motivation to PR it anymore.

> somebody to create an ungoogled-chromium.install package
When the time has come, I change one.

2023-07-30 16:48 UTC, closed without merging