(totalcommander) Add comment to confirm use of Chocolatey environment variables which fail Package Validator
chocolatey-community/chocolatey-packages pull request #2131
Opened 2023-01-25 20:12 UTC by pauby

## Description
Added a comment as to why a line of code, which fails Package Validator, is used and needed

## Motivation and Context
The use of specific Chocolatey environment variables fails Package Validator. It is used due to a bug in Chocolatey CLI. Added a comment as to why it is there so it can continue to be exempted from Package Validator until the bug is fixed at which time it should be refactored.

## How Has this Been Tested?
It hasn't. It's a comment.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- x ] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

2023-01-25 20:14 UTC, pauby commented
Once this is merged, the 10.52 version needs to be repushed to Chocolatey Community Repository.

2023-01-27 07:33 UTC, gep13 approved these changes
LGTM!

2023-01-27 07:35 UTC, gep13 commented
@pauby the change itself here is fine, but the AppVeyor build failed due to a timeout when actually attempting the installation. Did you see any similar issues during your testing?

2023-01-27 10:09 UTC, pauby commented
It was the uninstall that failed @gep13. The change I made wouldn't have affected that so I assumed they uninstall was broken. I was hoping to look at it this weekend as it may need rewritten.

2023-01-27 23:13 UTC, pauby commented
This failed AppVeyor but it is marked here as passed. Is that normal @AdmiringWorm ? The AU script is tested and working here but I may have missed something for AppVeyor.

2023-01-28 10:06 UTC, pauby commented
Having trouble finding this to a draft in the app. Please don't review or merge this until more changes are made.

2023-01-29 18:19 UTC, pauby commented
This is now ready for review and I'm expecting some changes to be requested.

2023-03-01 12:03 UTC, pauby commented
The [Total Commander 10.52 packages has been rejected](https://community.chocolatey.org/packages/TotalCommander/10.52). I have moved it back to submitted.

2023-03-24 09:38 UTC, AdmiringWorm requested changes
One small change, and a rebase then this can be merged in.

2023-03-24 09:38 UTC, AdmiringWorm commented on automatic/totalcommander/update.ps1
> +            '(^\s*file\s*=\s*)(".*")'      = "`$1""`$toolsPath\$(Split-Path -Path $Latest.Url32 -Leaf)"""
The call to `Get-RemoteFiles` sets `FileName32` and `FileName64`, so there is no need to do a split path on the URL itself.

```suggestion
            '(^\s*file\s*=\s*)(".*")'      = "`$1""`$toolsPath\$($Latest.FileName32)"""
```

2023-03-29 08:21 UTC, merged

2023-03-29 10:34 UTC, pauby commented
@AdmiringWorm Thank you for doing that. I had this on my todo list but hadn't manage to get to it yet.

2023-03-29 10:36 UTC, pauby commented
@AdmiringWorm was 10.52 pushed again? It's currently in the Submitted state waiting for another push.

2023-03-29 16:36 UTC, pauby commented
Awesome. Thanks @AdmiringWorm. The package is now approved.