K9s Include new Amd 64 version
chocolatey-community/chocolatey-packages pull request #2170
Opened 2023-03-10 09:39 UTC by danielkoek

In PR https://github.com/derailed/k9s/pull/1910 the x86_64 in the release was changed to amd64
so that :
`k9s_Windows_x86_64.tar.gz`
changed into
`k9s_Windows_amd64.tar.gz`

## Description
This will check for both and select the correct version

This will also close https://github.com/chocolatey-community/chocolatey-packages/issues/1999

## Motivation and Context
It is really annoying that it is still not up to date to the latest version available

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [X] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [X] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [X] The changes only affect a single package (not including meta package).

2023-03-10 10:57 UTC, pauby requested changes

2023-03-10 10:57 UTC, pauby commented on automatic/k9s/tools/chocolateyinstall.ps1
> +  FileFullPath64 = Get-Item $toolsDir\k9s_*Windows_*64.tar.gz
I know this code was pre-existing and you are just updating it. However, we want to remove `Get-Item` when looking for embedded binaries. Please reference the exact name of the embedded file here without using `Get-Item` or similar, to search for it.

2023-03-10 13:28 UTC, danielkoek commented on automatic/k9s/update.ps1
> +    URL64          = $LatestRelease.assets | Where-Object { ($_.name -eq 'k9s_Windows_x86_64.tar.gz') -or ($_.name -eq 'k9s_Windows_amd64.tar.gz') } | Select-Object -ExpandProperty browser_download_u
I figured it needed to be backwards compatible, but I will remove that so!

2023-03-13 13:00 UTC, danielkoek commented
Let me know if you are missing anything else!

2023-03-24 10:23 UTC, AdmiringWorm approved these changes
LGTM. I have taken the liberty to reword the commits you made and squashed them.

In the future, please try to word the commits you make appropriately and always use the package name inside parentheses as a prefix in both the PR title and the commit summary.

I am saying this now as we may start rejecting commits not worded correctly in the future.

2023-03-24 10:23 UTC, merged