(libreoffice-streams) Add NoDesktopIcon package parameter
chocolatey-community/chocolatey-packages pull request #2227
Opened 2023-05-08 05:55 UTC by slycordinator

## Description
Add '/NoDesktopIcon' package parameter to package
Setting --params '/NoDesktopIcon' appends 'CREATEDESKTOPLINK=0' to the end of the package's silentArgs variable.
When the parameter is unset, nothing happens because CREATEDESKTOPLINK=1 is set by default in libreoffice MSI installers.

## Motivation and Context
Allows user to disable the creation of the Desktop Icon / Desktop Shortcut.

## How Has this Been Tested?
I installed and uninstalled libreoffice-fresh and libreoffice-still packages with the --params '/NoDesktopIcon' set and unset, both in a running system and in the chocolatey-community test environment.

With '/NoDesktopIcon' unset, the packages installed with a desktop icon added, as expected.
With '/NoDesktopIcon' set, they installed with no desktop icon.

## Screenshot (if appropriate, usually isn't needed):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [X] My code follows the code style of this repository.
- [X] My change requires a change to documentation (this usually means the notes in the description of a package).
- [X] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [X] I have updated the package description and it is less than 4000 characters.
- [X] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [X] The added/modified package passed install/uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

2023-07-22 18:13 UTC, pauby commented
@slycordinator Can you point to the documentation that lists this as an acceptable silent installer argument?

2023-08-22 08:34 UTC, slycordinator commented
https://wiki.documentfoundation.org/Deployment_and_Migration

CREATEDESKTOPLINK (default=1) - create desktop shortcut icon (bugged in
4.1.0+, solved in tdf#65102 for 4.1.4 and 4.2.0)

On Sun, Jul 23, 2023, 3:13 AM Paul Broadwith ***@***.***>
wrote:

> @slycordinator <https://github.com/slycordinator> Can you point to the
> documentation that lists this as an acceptable silent installer argument?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chocolatey-community/chocolatey-packages/pull/2227#issuecomment-1646642694>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQN7DTOCJQJUOSXUMOUUOATXRQJ5HANCNFSM6AAAAAAXZPCCGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-08-24 23:17 UTC, pauby requested changes
Unfortunately, I can't test this, as locally I get this error:

```
PS C:\Users\WDAGUtilityAccount\Desktop\chocolatey-coreteampackages\automatic\libreoffice-streams> .\update.ps1
libreoffice-streams - checking updates using au version 2022.10.24

*** Stream: 7.5.3.fresh ***
WARNING: Invalid nuspec file Version '' - using 0.0
URL check
  https://downloadarchive.documentfoundation.org/libreoffice/old/7.5.3.2/win/x86/LibreOffice_7.5.3.2_Win_x86.msi
URL syntax is invalid:
At C:\Program Files\WindowsPowerShell\Modules\au\Public\Update-Package.ps1:110 char:67
+ ... heck_url $url -Options $Latest.Options) { throw "${res}:$url" } else  ...
+                                               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (URL syntax is invalid::String) [], RuntimeException
    + FullyQualifiedErrorId : URL syntax is invalid:
```

2023-08-24 23:17 UTC, pauby commented on automatic/libreoffice-streams/libreoffice-streams.nuspec
This file doesn't need to be amended as it is updated automatically.

2023-09-27 04:00 UTC, closed without merging