(tixati) Overhauled AHK script for v2
chocolatey-community/chocolatey-packages pull request #2275
Opened 2023-08-14 18:48 UTC by teknowledgist

This requires AHK v2 now, but it seems to be working.

## Description
Rewrote the AutoHotKey script to be compatible with AHKv2.

## Motivation and Context
The Tixoti package has an "open" dependency on AutoHotKey.  When V2 of AHK was realeased, it had significantly different syntax, and it broke this package (and many others).  The AHK script had to be rewritten.  Also, launching the installer from the ChocolateyInstall.ps1 script rather than from AHK seems more "proper".

## How Has this Been Tested?
`choco pack` and `choco install tixoti -s . -y` and `choco uninstall tixoti -y`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

2023-08-24 01:05 UTC, pauby commented
Can you go back to the checklist and confirm this has been tested in the Chocolatey Test Environment?

2023-09-05 18:38 UTC, teknowledgist commented
The install/uninstall worked in the Chocolatey Test Environment that I cloned.  I have updated the checklist.

2023-09-21 10:39 UTC, AdmiringWorm requested changes
The changes looks good to me, however can you please update your commits to use the prefix `(tixati) ` (similar to how the PR title is set).

As you are using your master branch as the head, I am unable to rebase and push on your behalf.

2023-09-21 13:18 UTC, teknowledgist commented
@AdmiringWorm I am woefully ignorant in the ways of Git(Hub), and I can't figure out how to change the commit (titles) to include the `(tixati) ` prefix.  

I guess I am "using [my] master branch as the head"(?), but I don't even know how else I could (or should) be doing it.

2023-10-26 04:00 UTC, closed without merging