(notepadplusplus.install) Add \NoStop install parameter to avoid kill…
chocolatey-community/chocolatey-packages pull request #2281
Opened 2023-08-21 19:47 UTC by opoplawski

…ing notepad++ processes

## Description
We would like to update packages automatically on peoples machines, but having the notepad++ processes killed is terribly disruptive.  This adds a `\NoStop` install parameter to allow admins to avoid this.

This is similar to #1919 

## How Has this Been Tested?
Built package locally and installed with:
`choco install notepadplusplus.install --debug --verbose --source . --params "/NoStop"`
and verified that a running notepad++ process was not killed.  Ran again without `--params "/NoStop"` and verified that notepad++ was killed and restarted.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

2023-08-24 00:58 UTC, pauby requested changes

2023-08-24 00:58 UTC, pauby commented on automatic/notepadplusplus.install/README.md
> +`choco install notepadplusplus.install --params "/NoStop"`
```suggestion
`choco install notepadplusplus.install --params='"/NoStop"'`
```

2023-08-24 00:58 UTC, pauby commented on automatic/notepadplusplus.install/notepadplusplus.install.nuspec
Don't make changes here as it will be overwritten by the contents of the README.md file.

2023-08-24 00:58 UTC, pauby commented on automatic/notepadplusplus.install/tools/chocolateyBeforeModify.ps1
> +  } else {
Don't use cuddled elses.

2023-08-24 01:00 UTC, pauby commented
Can you update the commit message to use the correct 'slash' for the parameter, and update the checklist in the original comment?

2023-09-23 04:00 UTC, closed without merging

2023-09-24 03:35 UTC, opoplawski commented
I've made the changes.  Sorry for the delay.  Is it possible to re-open this?

2023-09-25 08:41 UTC, pauby commented
@opoplawski Unfortunately not. Please open a new PR.