(cdburnerxp) move to manual
chocolatey-community/chocolatey-packages pull request #2428
Opened 2024-02-10 18:49 UTC by TheCakeIsNaOH

## Description

Moves the `cdburnerxp` files to the manual directory and removes the `update.ps1`

## Motivation and Context

Fixes #2427 

## How Has this Been Tested?

N/A, moving package files only

## Screenshot (if appropriate, usually isn't needed):

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- N/A The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

2024-02-10 21:28 UTC, AdmiringWorm requested changes

2024-02-10 21:28 UTC, AdmiringWorm commented on automatic/cdburnerxp/update.ps1
Don't delete the update file. This is still useful if we want to create a fix version, or if development suddenly is resumed at some point (although that is unlikely).

Any file called `update.ps1` is executed when a manual package is pushed through AppVeyor.

2024-02-10 21:28 UTC, AdmiringWorm commented on manual/cdburnerxp/cdburnerxp.nuspec
Can you also update the `packageSourceUrl` for the package?

I don't remember whether we update it automatically or not for manual packages (I don't think we do).

2024-02-10 21:43 UTC, TheCakeIsNaOH commented on manual/cdburnerxp/cdburnerxp.nuspec
Done.

2024-02-10 21:43 UTC, TheCakeIsNaOH commented on automatic/cdburnerxp/update.ps1
Done.

2024-02-18 14:14 UTC, AdmiringWorm approved these changes
LGTM, failure on AppVeyor is a known problem for manual packages.

2024-02-18 14:14 UTC, merged

2024-02-18 14:14 UTC, AdmiringWorm commented
@TheCakeIsNaOH your changes have been merged. Thanks for your contribution 👍