(cmakew)(cmake.install) Clarify the text around the PATH
chocolatey-community/chocolatey-packages pull request #2444
Opened 2024-03-20 08:48 UTC by pauby

## Description
I have added text based on #2442 to make it clearer the `cmake.exe` is not on the PATH as it is following the installer behaviour, and providing options.

## Motivation and Context
See #2442

## How Has this Been Tested?
This is README changes and `Write-Warning`s. No other code changes.

## Screenshot (if appropriate, usually isn't needed):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

2024-03-20 16:52 UTC, gep13 requested changes

2024-03-20 16:52 UTC, gep13 commented on automatic/cmake.install/tools/chocolateyInstall.ps1
> +Write-Warning "Note that this package follow the default behaviour of the 'cmake' installer and does not add cmake.exe to the PATH."
```suggestion
Write-Warning "Note that this package follows the default behaviour of the 'cmake' installer and does not add cmake.exe to the PATH."
```

2024-03-20 16:52 UTC, gep13 commented on automatic/cmake/Readme.md
> +For example: `choco install cmake --apply-install-arguments-to-dependencies 'ADD_CMAKE_TO_PATH=System'`
Shouldn't this be?

```suggestion
For example: `choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --apply-install-arguments-to-dependencies`
```

2024-03-20 17:42 UTC, pauby commented on automatic/cmake/Readme.md
> +For example: `choco install cmake --apply-install-arguments-to-dependencies 'ADD_CMAKE_TO_PATH=System'`
Fixed.

2024-03-21 09:36 UTC, gep13 approved these changes
LGTM!

2024-03-21 09:36 UTC, merged

2024-03-21 09:37 UTC, gep13 commented
@pauby thanks for getting this fixed up!