(nodejs.install) FIx auto-update by avoiding setting 32-bit URLs for NodeJS 23+
chocolatey-community/chocolatey-packages pull request #2557
Opened 2024-10-21 13:42 UTC by chadlwilson

## Description
As noted in #2556 the auto-update for NodeJS is broken as NodeJS dropped 32-bit support. This change at least should unblock the auto-update for other releases (priority should be v22 LTS patches coming through).

The v23 package itself will need some further work to handle cases where there is no 32-bit version gracefully. For now I only have time to try and unblock updates/patches for other versions, not address a non-LTS release like v23.

## Motivation and Context
Partially addresses #2556 to at least unblock auto-updates for NodeJS `< 23`.

## How Has this Been Tested?
Locally sanity tested the update script.

## Screenshot (if appropriate, usually isn't needed):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

2024-10-21 15:50 UTC, chadlwilson commented
I'm not sure of the canonical way to approach the optionality of the 32-bit installer in the `chocolateyInstall.ps1` but can follow up with a separate PR to improve the experience/error message if trying to install Node 23 on a 32-bit system (or if forcing a 32 bit install) if I get some tips or a similar package to model from.

2024-10-21 16:17 UTC, JPRuskin commented
Ah, hm. Yeah, we may need to do something with that install script - Chocolatey will handle things correctly if we pass file and file64 appropriately, the logic in there currently is a little unusual. Let me see if I can find an example.

2024-10-25 05:31 UTC, chadlwilson commented
@JPRuskin possible to get this merged to unblock these patch releases? Doesn't seem to make anything worse for now, so can make any tweaks to the v23 installers to make lack of 32-bit variant fail more cleanly later?

2024-10-25 12:49 UTC, AdmiringWorm requested changes
Since there have been a few days since @JPRuskin had a look, I decided to jump in on this one.

While the change itself looks fine, there are additional work needed to get this over the line.

As this is an embedded package, there is also a `VERIFICATION.txt` file that includes information about how to validate the package, as there is no 32bit URL, this file should not include any mentions of 32bit for v23 and later.

So additional work in this file is needed due to this.

2024-10-25 14:43 UTC, chadlwilson commented
OK. I dont know how to do that,.so I suppose I will abandon this PR.

I've no interest right now in making v23 work given it is a non LTS release. I simply wanted patch releases on LTS and upcoming LTS to come through again as 22.10.0 is now missing.and all security patches blocked.

If there was a way obvious to me to ignore auto-updates completely for v23+ I'd have submitted a PR to do that and decouple these two problems.

2024-10-25 17:04 UTC, closed without merging

2024-10-26 05:54 UTC, chadlwilson commented
If anyone else has time/energy/knowledge to pick this up the stuff apparently needed to get this done is mentioned at https://github.com/chocolatey-community/chocolatey-packages/issues/2556#issuecomment-2438036283