(inkscape) drop 32 bit support
chocolatey-community/chocolatey-packages pull request #2572
Opened 2024-11-17 04:03 UTC by TheCakeIsNaOH

## Description

As the 32bit version of inkscape has been dropped, remove support from package.

## Motivation and Context

Fixes  #2552

## How Has this Been Tested?

Tested on Win10 22H2 and in test env

## Screenshot (if appropriate, usually isn't needed):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

2024-12-02 10:37 UTC, AdmiringWorm requested changes
The removal looks good in general, however we also need to add a note in the `Readme.md` file that mentions the removal of 32bit support.

See the nodejs package as a quick example: https://github.com/chocolatey-community/chocolatey-packages/blob/96ebfb0edfba33e33c47f3fb449364128d0dca67/automatic/nodejs/README.md?plain=1#L11

2025-02-02 14:33 UTC, mgmax commented
@AdmiringWorm  friendly reminder :-) - If there are any improvements needed, please let us know

2025-02-05 09:07 UTC, flcdrg approved these changes

2025-02-08 03:50 UTC, merged

2025-02-08 03:51 UTC, corbob commented
Thanks for getting this fixed up @TheCakeIsNaOH 👍